# Generated by Django 4.0.2 on 2023-02-08 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_comment_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 12, 0, 14, 203485, tzinfo=utc)),
        ),
    ]
